export const REQUEST_GET_PRODUCT = "REQUEST_GET_PRODUCT";
export const SUCCESS_GET_PRODUCT = "SUCCESS_GET_PRODUCT";
export const FAILURE_GET_PRODUCT = "FAILURE_GET_PRODUCT";

export const REQUEST_ADD_PRODUCT = "REQUEST_ADD_PRODUCT";
export const SUCCESS_ADD_PRODUCT = "SUCCESS_ADD_PRODUCT";
export const FAILURE_ADD_PRODUCT = "FAILURE_ADD_PRODUCT";

export const REQUEST_REMOVE_PRODUCT = "REQUEST_ADD_PRODUCT";
export const SUCCESS_REMOVE_PRODUCT = "SUCCESS_ADD_PRODUCT";
export const FAILURE_REMOVE_PRODUCT = "FAILURE_ADD_PRODUCT";